version: 2
updates:
  - package-ecosystem: npm
    directory: /scraper
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'eslint'
          - '@eslint/*'
          - 'globals'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
